function createfigure2
%CREATEFIGURE2

%  Auto-generated by MATLAB on 06-Sep-2019 04:43:20

% Create figure
figure1 = figure;

% Create rectangle
annotation(figure1,'rectangle',...
    [0.344818681318681 0.313369963369964 0.369879120879121 0.443956043956046]);

